# Base name of the CSI Manila driver
# Enabled Manila share protocols
shareProtocols:
  - protocolSelector: NFS
    fsGroupPolicy: None
    fwdNodePluginEndpoint:
      dir: /var/lib/kubelet/plugins/csi-nfsplugin
      sockFile: csi.sock
  # - protocolSelector: CEPHFS
  #   fwdNodePluginEndpoint:
  #     dir: /var/lib/kubelet/plugins/cephfs.csi.ceph.com
  #     sockFile: csi.sock

replicas: 1
podAnnotations: {}

images:
  csi-driver-manila: image-repository:image-tag
  csi-provisioner: image-repository:image-tag
  csi-attacher: image-repository:image-tag
  csi-snapshotter: image-repository:image-tag
  csi-resizer: image-repository:image-tag
  csi-liveness-probe: image-repository:image-tag

socketPath: /var/lib/csi/sockets/pluginproxy
timeout: 3m
userAgentHeaders: []

resources:
  driver:
    requests:
      cpu: 20m
      memory: 50Mi
    limits:
      memory: 360Mi
  provisioner:
    requests:
      cpu: 11m
      memory: 38Mi
    limits:
      memory: 400Mi
  snapshotter:
    requests:
      cpu: 11m
      memory: 36Mi
    limits:
      memory: 220Mi
  resizer:
    requests:
      cpu: 11m
      memory: 32Mi
    limits:
      memory: 220Mi
  livenessProbe:
    requests:
      cpu: 11m
      memory: 32Mi
    limits:
      memory: 220Mi

vpa:
  resourcePolicy:
    driver:
      maxAllowed:
        cpu: 800m
        memory: 4G
    provisioner:
      maxAllowed:
        cpu: 800m
        memory: 4G
    snapshotter:
      maxAllowed:
        cpu: 700m
        memory: 3G
    resizer:
      maxAllowed:
        cpu: 700m
        memory: 3G
    livenessProbe:
      maxAllowed:
        cpu: 500m
        memory: 2G
