apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "csi-driver-manila-node.extensionsGroup" . }}:{{ include "csi-driver-manila-node.name" . }}:manila-nodeplugin
roleRef:
  kind: ClusterRole
  name: {{ include "csi-driver-manila-node.extensionsGroup" . }}:{{ include "csi-driver-manila-node.name" . }}:manila-nodeplugin
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: csi-manila-nodeplugin
    namespace: {{ .Release.Namespace }}
