kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-driver-manila-controller
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: shoot-access-csi-driver-manila
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: csi-driver-manila-controller
  apiGroup: rbac.authorization.k8s.io
